name: Manual Build Docs

on:
  workflow_dispatch:

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '18' # Use the Node.js version that matches your project's requirements

    - name: Install Dependencies
      run: npm ci # or 'npm install' if you prefer

    - name: Build Docs
      run: npm run docs:build
